export const Characters = `ELLARIA SAND
ROBB STARK
LORAS TYRELL
TYWIN LANNISTER
JAIME LANNISTER
STANNIS BARATHEON
DAVOS SEAWORTH
NED STARK
CERSEI LANNISTER
OBERYN MARTELL
JON SNOW
BRIENNE
XARO XHOAN DAXOS
MARGAERY TYRELL
JORAH MORMONT
RENLY BARATHEON
DAENERYS TARGARYEN
GREY WORM
DORAN MARTELL
HIZDAR ZO LORAQ
KRAZNYS MO NAKLOZ
PYAT PREE
CATELYN STARK
BARRISTAN SELMY
TYRION LANNISTER
AERO HOTAH
MELISANDRE
SALLADOR SAAN`;