export const EssosMap = `___CONTINENTS___
ESSOS
___REGIONS___
ANDALOS:ESSOS:4:FFFF00
THE DISPUTED LANDS:ESSOS:2:FFFF0F
LANDS OF LONG SUMMER:ESSOS:1:F0FF00
JADE SEA COAST:ESSOS:1:FFFF00
THE DOTHRAKI SEA:ESSOS:4:0FFF0F
SLAVER'S BAY:ESSOS:3:FF0000
___TERRITORIES___
BRAAVOSIAN COASTLANDS:ANDALOS:1:1:1:SIEGEENGINE
THE AXE:ANDALOS:1:0:0:FORTIFICATION
HILLS OF NORVOS:ANDALOS:0:0:0:KNIGHT
FOREST OF QOHOR:ANDALOS:1:0:1:SIEGEENGINE
THE FLATLANDS:ANDALOS:1:1:1:KNIGHT
UPPER RHOYNE:ANDALOS:0:0:0:FORTIFICATION
THE GOLDEN FIELDS:ANDALOS:0:0:0:SIEGEENGINE
MYR:THE DISPUTED LANDS:1:1:0:KNIGHT
LOWER RHOYNE:THE DISPUTED LANDS:0:0:0:FORTIFICATION
TYROSH:THE DISPUTED LANDS:1:0:1:FORTIFICATION
LYS:THE DISPUTED LANDS:1:1:0:KNIGHT
THE ORANGE SHORE:THE DISPUTED LANDS:1:0:0:SIEGEENGINE
VOLANTIS:THE DISPUTED LANDS:1:1:1:SIEGEENGINE
VALYRIA:LANDS OF LONG SUMMER:1:0:1:FORTIFICATION
OROS:LANDS OF LONG SUMMER:1:0:0:KNIGHT
THE SEA OF SIGHTS:LANDS OF LONG SUMMER:1:1:0:SIEGEENGINE
MANTARYS:LANDS OF LONG SUMMER:1:0:1:KNIGHT
SARNOR:THE DOTHRAKI SEA:1:0:1:SIEGEENGINE
WESTERN DOTHRAKI SEA:THE DOTHRAKI SEA:0:0:0:FORTIFICATION
NORTHERN DOTHRAKI SEA:THE DOTHRAKI SEA:1:0:0:KNIGHT
EASTERN DOTHRAKI SEA:THE DOTHRAKI SEA:1:0:0:SIEGEENGINE
LHAZAR:THE DOTHRAKI SEA:0:0:1:FORTIFICATION
VAES DOTHRAK:THE DOTHRAKI SEA:0:0:1:KNIGHT
THE FOOTPRINT:THE DOTHRAKI SEA:1:0:0:FORTIFICATION
MEEREEN:SLAVER'S BAY:1:1:1:FORTIFICATION
YUNKAI:SLAVER'S BAY:1:0:1:KNIGHT
ASTAPOR:SLAVER'S BAY:1:1:1:SIEGEENGINE
OLD GHIS:SLAVER'S BAY:1:0:0:KNIGHT
NEW GHIS:SLAVER'S BAY:1:1:0:SIEGEENGINE
THE RED WASTE:SLAVER'S BAY:1:1:1:FORTIFICATION
NORTHERN JADE SEA:JADE SEA COAST:1:0:0:SIEGEENGINE
SAMYRIAN:JADE SEA COAST:1:0:0:FORTIFICATION
BAYASABHAD:JADE SEA COAST:1:0:0:KNIGHT
QARTH:JADE SEA COAST:1:1:1:SIEGEENGINE
___CONNECTIONS___
THE AXE:BRAAVOSIAN COASTLANDS
THE AXE:HILLS OF NORVOS
THE AXE:FOREST OF QOHOR
HILLS OF NORVOS:UPPER RHOYNE
HILLS OF NORVOS:BRAAVOSIAN COASTLANDS
HILLS OF NORVOS:FOREST OF QOHOR
UPPER RHOYNE:THE GOLDEN FIELDS
UPPER RHOYNE:LOWER RHOYNE
UPPER RHOYNE:FOREST OF QOHOR
UPPER RHOYNE:THE FLATLANDS
UPPER RHOYNE:BRAAVOSIAN COASTLANDS
THE GOLDEN FIELDS:MYR
THE GOLDEN FIELDS:THE FLATLANDS
THE GOLDEN FIELDS:LOWER RHOYNE
MYR:TYROSH
MYR:THE FLATLANDS
MYR:LOWER RHOYNE
MYR:THE ORANGE SHORE
TYROSH:THE ORANGE SHORE
THE ORANGE SHORE:LYS
THE ORANGE SHORE:VOLANTIS
THE ORANGE SHORE:LOWER RHOYNE
VOLANTIS:LOWER RHOYNE
VOLANTIS:MANTARYS
MANTARYS:THE SEA OF SIGHTS
MANTARYS:LOWER RHOYNE
MANTARYS:WESTERN DOTHRAKI SEA
MANTARYS:MEEREEN
THE SEA OF SIGHTS:OROS
THE SEA OF SIGHTS:VALYRIA
OROS:VALYRIA
WESTERN DOTHRAKI SEA:FOREST OF QOHOR
WESTERN DOTHRAKI SEA:SARNOR
WESTERN DOTHRAKI SEA:EASTERN DOTHRAKI SEA
WESTERN DOTHRAKI SEA:NORTHERN DOTHRAKI SEA
WESTERN DOTHRAKI SEA:LOWER RHOYNE
WESTERN DOTHRAKI SEA:MEEREEN
EASTERN DOTHRAKI SEA:NORTHERN DOTHRAKI SEA
EASTERN DOTHRAKI SEA:VAES DOTHRAK
EASTERN DOTHRAKI SEA:SAMYRIAN
EASTERN DOTHRAKI SEA:THE RED WASTE
EASTERN DOTHRAKI SEA:LHAZAR
EASTERN DOTHRAKI SEA:MEEREEN
EASTERN DOTHRAKI SEA:THE FOOTPRINT
THE FOOTPRINT:NORTHERN JADE SEA
THE FOOTPRINT:VAES DOTHRAK
LHAZAR:MEEREEN
LHAZAR:YUNKAI
LHAZAR:THE RED WASTE
THE RED WASTE:SAMYRIAN
THE RED WASTE:BAYASABHAD
THE RED WASTE:QARTH
THE RED WASTE:OLD GHIS
THE RED WASTE:ASTAPOR
THE RED WASTE:YUNKAI
OLD GHIS:NEW GHIS
OLD GHIS:ASTAPOR
BAYASABHAD:SAMYRIAN
BAYASABHAD:QARTH
SAMYRIAN:NORTHERN JADE SEA
SAMYRIAN:VAES DOTHRAK
YUNKAI:MEEREEN
YUNKAI:ASTAPOR
VAES DOTHRAK:NORTHERN JADE SEA
SARNOR:NORTHERN DOTHRAKI SEA
SARNOR:FOREST OF QOHOR
FOREST OF QOHOR:LOWER RHOYNE
BRAAVOSIAN COASTLANDS:THE FLATLANDS
BRAAVOSIAN COASTLANDS:MYR
BRAAVOSIAN COASTLANDS:TYROSH
BRAAVOSIAN COASTLANDS:LYS
BRAAVOSIAN COASTLANDS:VOLANTIS
THE FLATLANDS:TYROSH
THE FLATLANDS:LYS
THE FLATLANDS:VOLANTIS
MYR:LYS
MYR:VOLANTIS
LYS:VOLANTIS
QARTH:MEEREEN
QARTH:ASTAPOR
QARTH:NEW GHIS
QARTH:SEA OF SIGHTS
MEEREEN:ASTAPOR
MEEREEN:NEW GHIS
MEEREEN:THE SEA OF SIGHTS
ASTAPOR:NEW GHIS
ASTAPOR:THE SEA OF SIGHTS
NEW GHIS:THE SEA OF SIGHTS`;