export const Maesters = `PIRATE SHIP FLEET:1
DESPERATE AMBUSH:1
LEAD INTO A TRAP:1
PREPARING FOR WAR:2
REINFORCE BULWARKS:2
SPIDER'S SABOTAGE:1
BRIBERY:1
A SWORN SWORD:2
STRENGTH OF STEEL:1
CASTLE WALLS:1
WEAPONS OF WAR:1
SICKNESS IN THE RANKS:1
MASS DESERTION:1
A WEB OF LIES:1
TAKEN CAPTIVE:1
VALRYIAN STEEL:1
SHIFTING ALLIANCE:1
ESTABLISH THE HIGH GROUND:1
CONFUSION IN THE RANKS:1
MOURNING THE FALLEN:1
WINTER IS COMING:1
CUT OFF SUPPLY LINES:1
FORTIFIED PORTS:1
HIRED THIEVES:1
BEST LAID PLANS:1
UNPLANNED LOSSES:1
A CALL TO ARMS:1
RAID THE COUNTRYSIDE:1
VALAR MORGHULIS:1
RALLY THE SMALLFOLK:1
WED FOR PEACE:1
STRAGETIC WITHDRAWL:1
A TEMPORARY TRUCE:1
FREEFOLK UPRISING:1
BLOOD MAGIC:1
CALL IN YOUR BANNERS:1`;