export const VictoryCards = `___POINTS_TO_WIN___
10
___VICTORY_CARDS___
CONTROL 1 KNIGHT, SIEGE ENGINE, AND FORTIFICATION:3
CONTROL 4 CASTLES AND 2 PORTS:1
CONTROL 3 PORTS:1
POSSESS 500 OR MORE GOLD:1
CONTROL 9 CASTLES:3
POSSESS 1000 OR MORE GOLD:2
CONTROL 5 CASTLES:1
POSSESS 1500 OR MORE GOLD:3
DESTROY 8 OPPOSING ARMIES IN A SINGLE TURN:2
CONTROL 7 CASTLES:2
CONQUER 2 TERRITORIES FROM ONE OPPONENT IN A SINGLE TURN:1
CONQUER 4 TERRITORIES FROM ONE OPPONENT IN A SINGLE TURN:3
CONTROL 3 TERRITORIES IN 4 REGIONS:4
CONTROL 8 CASTLES AND 6 PORTS:3
CONQUER 6 TERRITORIES IN A SINGLE TURN:3
CONQUER 3 TERRITORIES IN A SINGLE TURN:1
CONTROL A PORT ON EACH COASTAL AREA:1
CONTROL 2 REGIONS:3
CONTROL 2 TERRITORIES IN 3 REGIONS:2
CONQUER 5 TERRITORIES WITH A PORT IN A SINGLE TURN:4
CONTROL 6 CASTLES AND 4 PORTS:2
CONTROL 7 PORTS:3
CONTROL 5 PORTS:2
CONTROL 9 PORTS:4
DESTROY 12 OPPOSING ARMIES IN A SINGLE TURN:3
CONTROL 1 REGION:1
CONQUER 8 TERRITORIES IN A SINGLE TURN:4
POSSESS 2000 OR MORE GOLD:4
CONTROL 11 CASTLES:4
DESTROY 16 OPPOSING ARMIES IN A SINGLE TURN:4
CONTROL 10 CASTLES AND 8 PORTS:4
CONQUER 6 TERRITORIES WITH A CASTLE IN A SINGLE TURN:4
CONQUER 3 TERRITORIES WITH A CASTLE IN A SINGLE TURN:2
DESTROY 4 OPPOSING ARMIES IN A SINGLE TURN:1
CONQUER 3 TERRITORIES WITH A PORT IN A SINGLE TURN:2
CONTROL 2 KNIGHTS, SIEGE ENGINES, OR FORTIFICATIONS:2`;